# Generated by Django 4.2.5 on 2023-09-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordinal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
