# Generated by Django 4.2.5 on 2023-09-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_category_ordinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
