# Generated by Django 4.2.5 on 2023-10-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0007_remove_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('emotions', models.JSONField()),
            ],
        ),
    ]
