# Generated by Django 4.2.5 on 2023-10-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0009_remove_category_business_remove_review_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
