# Generated by Django 4.2.5 on 2023-10-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0010_alter_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('songs', models.JSONField()),
                ('emotions', models.JSONField()),
            ],
        ),
    ]
