# Generated by Django 4.2.5 on 2023-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0012_remove_playlist_emotions_remove_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='emotions',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
