# Generated by Django 4.2.5 on 2023-10-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0013_playlist_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
