# Generated by Django 4.2.5 on 2023-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0014_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='emotions',
            field=models.JSONField(verbose_name='emotions'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.JSONField(verbose_name='songs'),
        ),
    ]
